name: Test

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**.md"
      - "**.ts"
      - "deno.jsonc"
      - ".github/workflows/test.yml"

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno:
          - version: "2.0.0"
            # Remove lock file for unsupported lock file version
            remove-lock: true
          - version: "2.x"
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Remove deno.lock
        if: matrix.deno.remove-lock == true
        run: rm -f deno.lock

      - uses: denoland/setup-deno@v2
        with:
          deno-version: "${{ matrix.deno.version }}"

      - name: Check lint
        if: ${{ !cancelled() }}
        run: deno task check:lint

      - name: Check format
        if: ${{ !cancelled() }}
        run: deno task check:fmt

      - name: Check type
        if: ${{ !cancelled() }}
        run: deno task check:type

      - name: Check doc
        if: ${{ !cancelled() }}
        run: deno task check:doc

  check-publish:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        deno:
          - version: 2.x
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno.version }}

      - name: Check slow types
        run: deno task check:publish
